language: groovy

jdk:
- oraclejdk8

env:
  - GRAILS_VERSION=3.3.0

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
    - master

script: grails clean && grails upgrade --non-interactive && grails test-app --non-interactive --stacktrace
