language: groovy

jdk:
- oraclejdk8

env:
  - GRAILS_VERSION=3.3.0

before_install:
- sudo apt-get install grails $GRAILS_VERSION || true

branches:
  only:
    - master

script: grails clean && grails upgrade --non-interactive && grails test-app --non-interactive --stacktrace
